### PR TITLE
i love mart my friend my cool friend

### PR DESCRIPTION
**Pull request by webcatzz**
i love you mart

### CODE REVIEW

**Comment by murumart** [comment]
Is the gun sprite drawn by you? if you can't provide the rights to it then I'm gonna kill you.

**Comment by webcatzz** [comment]
The woods. Teleport to the woods

**Comment by murumart** [comment]
Explode????

**Comment by webcatzz** [comment]
& Explode & Forever

**Comment by radiohotline** [comment]
radiohotline

**Pull request merged**
